### PR TITLE
Spec fixes

### PR DESCRIPTION
**Pull request by sanjayankur31**
Hello!

I updated the spec with the necessary changes. Each commit is one change, so you can sort go through them to see each step.

The package builds now, but it won't yet install because the pebble maintainer hasn't built it for Fedora 33. I've filed a bug there now.

### CODE REVIEW

**Comment by anilbey** [comment]
Thanks for the updates! 
For some reason neuron is not installed. I get this error below when I try to run the tests.

`ERROR: Failure: ImportError (No module named 'neuron')`

This was not happening in with this spec file: https://github.com/anilbey/bluepyopt-rpm/blob/4f07da78b2fc6fe0fff9db56e092abfc37c450a0/python-bluepyopt.spec

Also I'm wondering if it's a good practice to make the tests part of the installation?

**Comment by sanjayankur31** [comment]
> Thanks for the updates!
> For some reason neuron is not installed. I get this error below when I try to run the tests.
> 
> `ERROR: Failure: ImportError (No module named 'neuron')`
> 

We'll need to include `BuildRequires: python3-neuron` and so on for all packages that are needed during the build, even for the tests.

> This was not happening in with this spec file: https://github.com/anilbey/bluepyopt-rpm/blob/4f07da78b2fc6fe0fff9db56e092abfc37c450a0/python-bluepyopt.spec

I don't think the tests were enabled then because the `bcond..` line wasn't in the spec.

> 
> Also I'm wondering if it's a good practice to make the tests part of the installation?

Yes, we run as many tests as possible as part of the build---because this helps confirm that the software works correctly on all Fedora releases and architectures with the different versions of dependencies that they may have.

**Comment by anilbey** [comment]
Neuron as a BuildRequire is required even without the tests otherwise we cannot use BluePyOpt. 
With that change, now I can run the examples such as this one `/BluePyOpt/bluepyopt/ephys/examples/simplecell`.

I pushed the change here: https://github.com/sanjayankur31/bluepyopt-rpm/commit/af222394f263de87f6ab4d1d33da595d918ea28b 
Weird, it's not reflected on this page.

**Comment by anilbey** [comment]
Something is wrong with GitHub today.

**Comment by sanjayankur31** [comment]
> Neuron as a BuildRequire is required even without the tests otherwise we cannot use BluePyOpt.

No, they are two different things. If something is required for BluePyOpt to run, it's a "Requires". If it is required during the build, it's a "BuildRequires". 

> With that change, now I can run the examples such as this one `/BluePyOpt/bluepyopt/ephys/examples/simplecell`.

How are you running these? As part of the build or did you install the rpm you're generating? When you install the rpm you generate, python3-neuron will be installed with it as a run-time dependency since it's listed as `Require: python3-neuron` and everything should work.

If you are running the examples as part of the build, or running the tests in the build and neuron is required to run them, then we need to `BuildRequire: python3-neuron`.

**Comment by sanjayankur31** [comment]
> I pushed the change here: [sanjayankur31@af22239](https://github.com/sanjayankur31/bluepyopt-rpm/commit/af222394f263de87f6ab4d1d33da595d918ea28b)
> Weird, it's not reflected on this page.

Not sure if you can push to my fork. I expect you'll have to merge my PR first and then make any other changes?

Can you please drop a comment on the review on bugzilla once you think it's ready? We need to continue the review there for you to be able to import the package into Fedora.

**Comment by anilbey** [comment]
> How are you running these? As part of the build or did you install the rpm you're generating? When you install the rpm you generate, python3-neuron will be installed with it as a run-time dependency since it's listed as `Require: python3-neuron` and everything should work.

I am installing the rpm and then running the python files. 

> No, they are two different things. If something is required for BluePyOpt to run, it's a "Requires". If it is required during the build, it's a "BuildRequires".

But for some reason `import neuron` does not work after installing the python3-bluepyopt rpm package without specifying neuron as `BuildRequires`.

> If you are running the examples as part of the build, or running the tests in the build and neuron is required to run them, then we need to BuildRequire: python3-neuron.

The tests should always be running but without  `BuildRequires: python3-neuron` BluePyOpt does not work. 
How can I run the tests as part of the build? I couldn't find it in the documentation.

> Not sure if you can push to my fork. I expect you'll have to merge my PR first and then make any other changes?

I should be able to push to the PR fork by default unless you deselected the "Allow edits from maintainers" box. The change I made should have been reflected here but it didn't. I assume it is due to the degradation on Github services this morning: https://www.githubstatus.com/

**Comment by anilbey** [comment]
> Can you please drop a comment on the review on bugzilla once you think it's ready? We need to continue the review there for you to be able to import the package into Fedora.

Yes sure. It is actually ready on my side. It works with https://github.com/sanjayankur31/bluepyopt-rpm/commit/af222394f263de87f6ab4d1d33da595d918ea28b on top of your commits.
GitHub is still malfunctioning though.

This PR is both merged and not merged at the same time.

Here it is merged and my last commit is considered part of it but somehow not merged but still recognised as the same PR.

github_bug

Here this PR is not merged but the merge button is not there as if it is already merged and all of the commits before this morning are merged to the master branch.

github_bug2

I have never seen GitHub behaving this awkward before.

**Comment by sanjayankur31** [comment]
> > How are you running these? As part of the build or did you install the rpm you're generating? When you install the rpm you generate, python3-neuron will be installed with it as a run-time dependency since it's listed as `Require: python3-neuron` and everything should work.
> 
> I am installing the rpm and then running the python files.
> 
> > No, they are two different things. If something is required for BluePyOpt to run, it's a "Requires". If it is required during the build, it's a "BuildRequires".
> 
> But for some reason `import neuron` does not work after installing the python3-bluepyopt rpm package without specifying neuron as `BuildRequires`.

That shouldn't happen. The `BuildRequire` doesn't do anything related to build-time dependencies at all. You can check the requires attached to the python3-bluepyopt rpm using this command:


```
rpm -qp --requires <full path to rpm file>

# So, something like:

rpm -qp --requires ./python3-bluepyopt*rpm

```

It should list neuron there. Let's continue this on the bugzilla ticket. The spec looks almost ready now.

**Pull request closed without merging**
